### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by AndreC10002** [r-cybersecurity/list-of-security-resources-for-ukraine#10]
Services offered by: Malware Patrol

Source of information: Please see pinned post on LinkedIn - https://www.linkedin.com/company/malware-patrol/

Services being offered: Free 6 months DNS Firewall service subscription

Who is eligible: Ukraine-based companies and government entities

How are the services accessed: Complete our DNS Firewall evaluation form and put "Ukraine based" in the comments. Then, follow the instructions to set up an evaluation call with us so we can discuss the set-up for your security environment. https://www.malwarepatrol.net/dns-firewall-evaluation-request/?source=ukraine

**Comment by tweedge** [comment]
Thank you!
