### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by GnosticPhaedrus** [r-cybersecurity/list-of-security-resources-for-ukraine#11]
Services offered by: [edited 19-03-22: Phaedrus]

Services offered: [Threat Intelligence and Mitigation]

Who is eligible: [all]

How are the services accessed: [email jcoverstone@gmail.com]

**Comment by tweedge** [comment]
Hi, is there a link to the source for this information?

**Comment by tweedge** [comment]
Closing as stale, sorry - please reopen if you can provide a source

**Comment by GnosticPhaedrus** [comment]
Would linkedin suffice?

**Comment by tweedge** [comment]
Sure!

**Comment by GnosticPhaedrus** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.linkedin.com/in/joshua-coverstone-4623bba7&ved=2ahUKEwje2oSVq6r2AhWzOn0KHWfkC60Qjjh6BAgFEAE&usg=AOvVaw2Y2bRfFZlUAJgEdvir_olI

Sorry for late reply

**Comment by GnosticPhaedrus** [comment]
https://www.linkedin.com/in/joshua-coverstone-4623bba7&ved=2ahUKEwje2oSVq6r2AhWzOn0KHWfkC60Qjjh6BAgFEAE&usg=AOvVaw2Y2bRfFZlUAJgEdvir_olI

**Comment by tweedge** [comment]
Works, added!

**Comment by GnosticPhaedrus** [comment]
Would you mind changing my name to "Phaedrus " and only listing my email
address? (To provide some anonymity). I apologize for the late change
 Is that a problem?

Thanks!
Josh

**Comment by tweedge** [comment]
Certainly and no trouble at all, thanks!

**Comment by tweedge** [comment]
Implemented in commit 2af575c4713dcf797cf9acc685e06493d6b31b79, and I'll make sure the issue text here is cleaned up too.
