### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by ghost** [r-cybersecurity/list-of-security-resources-for-ukraine#12]
**Please fill out all data in [brackets].**

Services offered by: Kontinuum and Shiva Maharaj the owner

Source of information: I am the owner of Kontinuum. And the notes in this episode. https://anchor.fm/amplifiedandintensified/episodes/PSA-Helping-to-secure-those-in-need-e1etjn7

Services being offered: Free Security assessments and free remediation if in our skill set, 30 days free NGAV with SOC monitoring/threat Intel for workstations, servers, mobile devices, real time IP address scanning an blocking of traffic on firewalls. The 30 days can be extended as needed per conditions in Ukraine and heightened alert levels. 

Who is eligible: freelance journalists, Ukranians, anyone helping the Ukrainian effort or any company stateside. 

How are the services accessed: please send an email to info@kontinuum.com and we will get in touch with you to help where and how we can.

**Comment by tweedge** [comment]
Fantastic, adding this now, thank you!
