### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by enteriaza** [r-cybersecurity/list-of-security-resources-for-ukraine#13]
**Please fill out all data in [brackets].**

Services offered by: Private Individual

Source of information: 
![image](https://user-images.githubusercontent.com/17418067/155906160-9241aaea-13f1-41fb-b9a0-4759c5c86c63.png)

Services being offered: eBGP Network peering to filter Malicious IP space, Botnets, Tornodes, etc. actively targeting Ukrainian resources, on BGP capable network devices

How are the services accessed: Network Engineers / IT Technicians need to contact me in order to setup eBGP peering sessions between their network devices and my eBGP network peer.

This is a service that I have designed myself and use actively at work to protect our internal/public network infrastructure.  I am the network manager employed by Africa's largest Online Payment Processor (DPO Group).  I am willing and able to open this service to the greater Internet community in order to protect their network infrastructure as well.  For verification purposes my email is [redacted], however, interested parties can contact me on ukraine@opticnetworks.net

Thanks,
Chris.

**Comment by tweedge** [comment]
Emailed for validation

**Comment by tweedge** [comment]
Confirmed, also redacted private email from issue
