### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by CRICyber** [r-cybersecurity/list-of-security-resources-for-ukraine#15]
**Please fill out all data in [brackets].**

Services offered by: [**Cyber Readiness Institute (CRI)**]

Source of information: [www.becyberready.com]

Services being offered: [The Cyber Readiness Institute (CRI) provides free, easy-to-use tools and resources to help small and medium-sized businesses (SMBs) around the world become more cyber-secure and resilient. CRI’s resources and practical guides focus on human behavior and place significant emphasis on employee education and awareness.]

Who is eligible: [All users can access CRI’s free cyber tools and resources.]

How are the services accessed: [Visit www.becyberready.com]

**Comment by tweedge** [comment]
Hi, while we appreciate the free resources that the cybersecurity community brings, I think we're going to keep this as normally-paid opportunities to get access to broader platforms & tools. There are a lot of resources companies (should) take advantage of but would take more effort to operationalize than say enterprise-ready platforms. If there is continued interest in this we may create a separate list though and will keep track of this in that case, thank you!
