### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by RoyGol** [r-cybersecurity/list-of-security-resources-for-ukraine#16]
**Please fill out all data in [brackets].**

Services offered by: [Minerva Labs]

Source of information: [[link, or link to screenshot](https://campaign.minerva-labs.com/ukraine-defense/)]

Services being offered: [Endpoint Security for Windows systems (including legacy systems) - Free of charge for 6 months. Unlimited endpoints]

Who is eligible: [Ukrainian Organizations]

How are the services accessed: [They need to sign up with the form and Minerva will contact them and set them up with an account and help them get started]

**Comment by tweedge** [comment]
Much appreciated, adding!
