### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by hauptmannziegler** [r-cybersecurity/list-of-security-resources-for-ukraine#17]
**Please fill out all data in [brackets].**

Services offered by: MindWise-Cybersecurity and Fraud Prevention

Source of information: https://www.mindwise.io/ukraine-cybersecurity-aid

Services being offered: Account Takeover Detection, Data Breach Detection, Threat Intelligence

Who is eligible: Ukrainian organizations such as businesses, corporations, or governments

How are the services accessed:  email ukraine@mindwise.io or schedule a meeting through our website https://www.mindwise.io/ukraine-cybersecurity-aid

**Comment by tweedge** [comment]
Great, thank you!
