### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by drhodeswork** [r-cybersecurity/list-of-security-resources-for-ukraine#18]
**Please fill out all data in [brackets].**

Services offered by: Silent Breach

Source of information: (https://silentbreach.com/News/silent-breach-offers-ukrainian-orgs-free-cybersecurity-tools/)

Services being offered: Quantum Armor,  Silent Breach's Attack Surface management platform, including cloud security and threat intelligence

Who is eligible: All Ukrainian orgs.

How are the services accessed: A free version can be accessed directly via qarmor.io but for full permissions (which is free for all Ukrainian orgs) potential clients will need to contact an account manager to get set up and trained in. This can be done within 72 hours of initial contact.

**Comment by tweedge** [comment]
Great, thank you!
