### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by alrferreira** [r-cybersecurity/list-of-security-resources-for-ukraine#19]
**Please fill out all data in [brackets].**

Services offered by: NETDEEP

Source of information: [[https://www.linkedin.com/feed/update/urn:li:activity:6907696903765770240]]

Services being offered: [Network Firewall and Cybersecurity Defensive Services]

Who is eligible: [Ukranians companies]

How are the services accessed: [https://www.netdeep.com.br/firewall/]

**Comment by tweedge** [comment]
Much appreciated! Adding now
