### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by Krivoblotsky** [r-cybersecurity/list-of-security-resources-for-ukraine#23]
Services offered by: MacPaw Inc.

Source of information: https://macpaw.com/news/data-protector-spy-buster

Services being offered: Static analysis to identify potentially unwanted Russian and Belorussian software, dynamic analysis to monitor outgoing traffic to detect and block unwanted connections to Russian servers.  

Who is eligible: All.

How are the services accessed: https://research.macpaw.com/spy-buster/

**Comment by tweedge** [comment]
Hello! Catching up on this. I've added this resource in [5783e03](https://github.com/r-cybersecurity/list-of-security-resources-for-ukraine/commit/5783e03439b108096bbad1a51ee06e47f2d45828) - cheers!
