### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by nekosheen** [r-cybersecurity/list-of-security-resources-for-ukraine#24]
Services offered by: CybelAngel

Source of information: https://cybelangel.com/blog/message-on-ukraine/

Services being offered: Cybelangel offers 24/7 monitoring services to detect cyber exposure of critical assets at no charge

Who is eligible: 
**Ukrainian private companies** who wish to asses their digital exposure in Ukraine
**NGOs active in the war** who wish to minimize the risks of their missions being interrupted by cyber attacks

How are the services accessed: In the form of an internet-based SaaS platform where incident reports can be securely accessed by Security teams of eligible organizations (first contact to be made by email [standing-together@cybelangel.com](mailto:standing-together@cybelangel.com))

**Comment by tweedge** [comment]
Fantastic, thank you! Adding now
