### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by JingcongZhao01** [r-cybersecurity/list-of-security-resources-for-ukraine#25]
Services offered by: [Hyperproof](hyperproof.io) 

Source of information: https://hyperproof.io/cyber-defense-solution/

Services being offered: Hyperproof's compliance operations software (sold typically as an annual subscription) is available for free to all eligible companies for one full year. The software includes a risk register, capabilities for assessing and managing security controls, documenting issues and remediation plans, and automated alerting and monitoring capability for risks and security controls. 

Who is eligible: All western companies in the United States and in the European Union which are classified as critical infrastructure sectors. For US companies, we use the definition from CISA. According to[ CISA](https://www.cisa.gov/critical-infrastructure-sectors), there are 16 critical sectors “whose assets, systems, and networks, whether physical or virtual are considered so vital to the United States that their incapacitation or destruction would have a debilitating effect on security, national economic security, national public health, or any combination thereof.” For EU companies, we use the definition from [Council Directive 2008/114/EC](https://eur-lex.europa.eu/legal-content/en/TXT/?uri=CELEX:32008L0114).

How are the services accessed: Request access at https://hyperproof.io/cyber-defense-solution/  A rep from Hyperproof will be in touch with the person who made the request, have a quick call to confirm key details including eligibility, and then provision the software to any eligible organization.

**Comment by tweedge** [comment]
Fantastic, adding now. Thank you!
