### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by Cyber-Light** [r-cybersecurity/list-of-security-resources-for-ukraine#26]
**Please fill out all data in [brackets].**

Services offered by: Vectra AI

Source of information: https://www.vectra.ai/forms/complimentary-security-tools-services-in-response-to-the-conflict-in-ukraine

Services being offered: Threat detection and response in hybrid and multi-cloud enterprises:
- Scan Microsoft Azure AD and M365 environments for signs of attack activities
- Monitor AWS infrastructure for signs of active attacks, in addition to provision of detection and response for both the network and control plane of AWS accounts
- Surveil network infrastructure both on-premises and in the cloud for signs of attack, including deployment of Vectra sensors that are purpose-built to detect malicious behavior
- Support the retention of historical metadata to aid incident response investigations based on indicators of compromise (IOCs) for specific attack variants.

Who is eligible: any organizations who believe they may be targeted as a result of the current conflict

How are the services accessed: Fill a form to request free Complimentary Security Tools & Services

**Comment by tweedge** [comment]
Fantastic, adding now. Thank you!
