### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by newmoneybigbucks** [r-cybersecurity/list-of-security-resources-for-ukraine#7]
**Please fill out all data in [brackets].**

Services offered by: [company name or expert name]
TCPdirect.   
Source of information: [link, or link to screenshot]
https://twitter.com/tcpdirect/status/1497017919917678593

Services being offered: [please list, ex. Incident Response services, Threat Intelligence, etc.]
They are offering hosting with filtered v4s that can sustain heavy traffic 
Offering to spin up VPNs
Who is eligible: [ex. all EU-based NATO members, just Ukrainians, just Ukrainian journalists, or unknown? be accurate to the source]
They are offering to spin up VPNs for people in Germany, Luxembourg, and the US. 
They do not mention who the rest of the services are for but they normally offer free hosting to everyone, so it can be assumed the hosting has completely open eligibility.
How are the services accessed: [ex. do people not need to sign up at all, do they need to sign up, contact a sales rep, or is this unknown? be accurate to the source]
twitter: @tcpdirect 
email: support@akamai.services 
irc: [@ircdchat](https://twitter.com/ircdchat)
 [#tcpdirect](https://twitter.com/search?q=%23tcpdirect&src=hashtag_click)

**Comment by Oscar-Geare** [comment]
Thank you. I'm interpreting "We can spin up VPNs for folks in Germany, Luxembourgh and all over the U.S" as "these are the places we can spin up VPN endpoints" not "these are the people eligible for the service", and have noted as such on the main page until otherwise clarified.
