### ISSUE TITLE
Consulting / Expert Advice

### ISSUE THREAD

**Issue by mthiessmeier** [r-cybersecurity/list-of-security-resources-for-ukraine#8]
**Please fill out all data in [brackets].**

Services offered by: [company name or expert name] Michael Thiessmeier (Expert),Allied Cyberpartners (company)

Source of information: [link, or link to screenshot]
https://www.linkedin.com/posts/michaelthiessmeier_ukraine-cybersecurity-alliedcyberpartners-activity-6899690456368709632-DDI2

Services being offered: [please list, ex. Incident Response services, Threat Intelligence, etc.]
Personal Security & Cybersecurity consulting (individuals and organizations )

Who is eligible: [ex. all EU-based NATO members, just Ukranians, just Ukrainian journalists, or unknown? be accurate to the source]

Ukrainians and Ukrainian Organizations

How are the services accessed: [ex. do people not need to sign up at all, do they need to sign up, contact a sales rep, or is this unknown? be accurate to the source]

Contact directly on LinkedIn or by emailing ukraine@alliedcyberpartners.com

**Comment by Oscar-Geare** [comment]
Added. Thank you!
