### ISSUE TITLE
New Security Resource for Ukraine

### ISSUE THREAD

**Issue by inprodwetest** [r-cybersecurity/list-of-security-resources-for-ukraine#9]
**Please fill out all data in [brackets].**

Services offered by: Palo Alto Networks

Source of information: https://unit42.paloaltonetworks.com/preparing-for-cyber-impact-russia-ukraine-crisis/

Services being offered: Threat Intelligence

Who is eligible: All

How are the services accessed: The Unit 42 website provides a free [ATOM](https://unit42.paloaltonetworks.com/atoms/gamaredon/) which contains a structured mapping of the Gamaredon group’s tactics aligned to MITRE’s ATT&CK framework.

**Comment by Oscar-Geare** [comment]
@tweedge is this something we want to include? It doesn't appear as though they are specifically offering anything they don't already do, no indication that this is free, etc.

**Comment by tweedge** [comment]
@rkaramchedu is there any specific commitment PAN has made to support Ukraine? This seems like them doing business as usual.

**Comment by inprodwetest** [comment]
It appears that it is business as usual and cannot tell if they went out of
the normal biz to provide anything -- having said that, there is a free
resource that may be of value? which prompted my submission for evaluation.

*"On the Unit 42 website, you will also find a free ATOM which contains a
structured mapping of the Gamaredon group’s tactics aligned to MITRE’s
ATT&CK framework."*

**Comment by tweedge** [comment]
Got it, I think let's hold this and see how things develop/if there's interest for more data. There are a *lot* of free/business as usual resources companies (should) take advantage of but would take more effort to operationalize than say enterprise-ready platforms. :)
